In [27]:
import numpy as np 
import pandas as pd 
from textblob import TextBlob
import matplotlib.pyplot as plt

# Reading CSV file

In [310]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/TSLAtweets5k.csv'
df_2 = pd.read_csv(file, sep=',')
print(df_2.head())

   Unnamed: 0    User_id                                            Message  \
0           0  353007388  $TSLA  SpaceX Is Launching a Rocket the Size o...   
1           1  353007192  $TSLA has been mentioned 3 times on WallStreet...   
2           2  353006941  Recap 7/6:\nGreat start to the week. $SPY puts...   
3           3  353006805  $SPY $TSLA \n\nhttps://mobile.twitter.com/Clar...   
4           4  353006152  $AMC For change you have to work together.\n-T...   

         Date       Time Sentiment  
0  2021-07-07  01:04:41Z       NaN  
1  2021-07-07  01:03:57Z       NaN  
2  2021-07-07  01:02:56Z       NaN  
3  2021-07-07  01:02:26Z   Bearish  
4  2021-07-07  00:59:51Z   Bullish  


In [311]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/AAPLtweets5k.csv'
df_1 = pd.read_csv(file, sep=',')
print(df_1.head())

   Unnamed: 0    User_id                                            Message  \
0           0  352604057             $AAPL time to take it to 150 in 1 week   
1           1  352603862  $AAPL In the recent reporting quarter: 25.00% ...   
2           2  352603771  $AAPL We know what a difficult time it has bee...   
3           3  352603702  $AAPL has a Return On Assets of 22.63%. This i...   
4           4  352603496                             $AAPL  Slowly going up   

         Date       Time Sentiment  
0  2021-07-06  08:03:11Z   Bullish  
1  2021-07-06  08:01:29Z       NaN  
2  2021-07-06  08:00:35Z       NaN  
3  2021-07-06  08:00:00Z       NaN  
4  2021-07-06  07:57:34Z   Bullish  


In [354]:
df_2
df_2['Date'] = pd.to_datetime(df_2['Date'])
pred_data = df_2[(df_2['Date'] >= '2021-06-01')]
pred_data.head()
pred_data.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/TSLA_to_pred_data.csv', sep = ',',index = False)

In [312]:
df = pd.concat([df_1, df_2], ignore_index=True)
print(df.head())

   Unnamed: 0    User_id                                            Message  \
0           0  352604057             $AAPL time to take it to 150 in 1 week   
1           1  352603862  $AAPL In the recent reporting quarter: 25.00% ...   
2           2  352603771  $AAPL We know what a difficult time it has bee...   
3           3  352603702  $AAPL has a Return On Assets of 22.63%. This i...   
4           4  352603496                             $AAPL  Slowly going up   

         Date       Time Sentiment  
0  2021-07-06  08:03:11Z   Bullish  
1  2021-07-06  08:01:29Z       NaN  
2  2021-07-06  08:00:35Z       NaN  
3  2021-07-06  08:00:00Z       NaN  
4  2021-07-06  07:57:34Z   Bullish  


# Data Cleaning

In [313]:
df.describe()

Unnamed: 0       User_id
count  299986.000000  2.999860e+05
mean    74996.000030  3.315685e+08
std     43299.321683  1.434288e+07
min         0.000000  2.997594e+08
25%     37498.000000  3.225103e+08
50%     74996.000000  3.330402e+08
75%    112494.000000  3.429894e+08
max    149995.000000  3.530074e+08

In [314]:
pip install textblob

In [316]:
data = df.drop(['User_id','Unnamed: 0'],axis = 1)
data.reset_index(drop=True, inplace=True)
data.dropna(inplace=True)
data.head()


Message        Date       Time  \
0              $AAPL time to take it to 150 in 1 week  2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up  2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t...  2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed...  2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t...  2021-07-06  07:38:41Z   

   Sentiment  
0    Bullish  
4    Bullish  
6    Bullish  
7    Bearish  
11   Bullish

In [317]:
data["Sentiment"].replace({"Bullish": "1", "Bearish": "0"}, inplace=True)
data.head()

Message        Date       Time  \
0              $AAPL time to take it to 150 in 1 week  2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up  2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t...  2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed...  2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t...  2021-07-06  07:38:41Z   

   Sentiment  
0          1  
4          1  
6          1  
7          0  
11         1

In [318]:
data = data.astype({'Sentiment': 'int32'})
data.dtypes

Message      object
Date         object
Time         object
Sentiment     int32
dtype: object

In [319]:
data['Date'] = pd.to_datetime(data['Date'])
data.head()

Message       Date       Time  \
0              $AAPL time to take it to 150 in 1 week 2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up 2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t... 2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed... 2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t... 2021-07-06  07:38:41Z   

    Sentiment  
0           1  
4           1  
6           1  
7           0  
11          1

In [320]:
tweets = data['Message']
print(tweets[4])

$AAPL  Slowly going up


In [28]:
pip install langdetect

  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993227 sha256=8e249feb667af40e3b3f8785c073139ce096342c33a1b8f4aaaf7203f0fe1420
  Stored in directory: c:\users\harshul\appdata\local\pip\cache\wheels\13\c7\b0\79f66658626032e78fc1a83103690ef6797d551cb22e56e734
Successfully built langdetect
Note: you may need to restart the kernel to use updated packages.


In [321]:
import nltk
import re
from nltk.corpus import stopwords

def text_cleaning(text):
    forbidden_words = set(stopwords.words('english'))
    text = ' '.join(text.split('.'))
    text = re.sub('\/',' ',text)
    text = text.strip('\'"')
    text = re.sub(r'@([^\s]+)',r'\1',text)
    text = re.sub(r'\\',' ',text)
    text = text.lower()
    text = re.sub('[\s]+', ' ', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)
    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))',' ',text)
    text = re.sub(r'((http)\S+)','',text)
    text = re.sub(r'\s+', ' ', re.sub('[^A-Za-z]', ' ', text.strip().lower())).strip()
    text = re.sub(r'\W+', ' ', text.strip().lower()).strip()
    text = [word for word in text.split() if word not in forbidden_words]
    return ' '.join(text)

data['Message'] = data['Message'].apply(lambda text: text_cleaning(text))
data.sample(3)

Message       Date  \
76255                                           told aapl 2021-04-28   
147173           aapl gosh please help apple follow trend 2021-03-08   
21523   gm aapl flight apple shares either way flight ... 2021-06-16   

             Time  Sentiment  
76255   20:46:21Z          1  
147173  14:05:50Z          1  
21523   17:05:12Z          1

In [325]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0

L=[]
for row in data['Message']:
    if len(row) >= 3:
        L.append(detect(row))
    else:
        L.append(None)

data['lang'] = L
data.head()

Message       Date       Time  \
0                                 aapl time take week 2021-07-06  08:03:11Z   
4                                   aapl slowly going 2021-07-06  07:57:34Z   
6   sndl many things billion bank debt free cannab... 2021-07-06  07:49:10Z   
7   smartoptions unusual activity alert delayed aa... 2021-07-06  07:44:42Z   
11    aapl time covered calls think reaching cautious 2021-07-06  07:38:41Z   

    Sentiment lang  
0           1   af  
4           1   en  
6           1   en  
7           0   en  
11          1   en

In [326]:
data = data[data["lang"] == 'en']
data.head()

Message       Date       Time  \
4                                   aapl slowly going 2021-07-06  07:57:34Z   
6   sndl many things billion bank debt free cannab... 2021-07-06  07:49:10Z   
7   smartoptions unusual activity alert delayed aa... 2021-07-06  07:44:42Z   
11    aapl time covered calls think reaching cautious 2021-07-06  07:38:41Z   
12  smartoptions unusual activity alert delayed aa... 2021-07-06  07:38:31Z   

    Sentiment lang  
4           1   en  
6           1   en  
7           0   en  
11          1   en  
12          0   en

In [328]:
data.describe()

Sentiment
count  110980.000000
mean        0.719724
std         0.449136
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000

In [327]:
data['Sentiment'].astype('int64').sum()

79875

In [3]:
data.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/my_clean_tweets.csv', sep = ',',index = False)

tweets=pd.read_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/my_clean_tweets.csv', sep=',')
tweets.sample(10)

Message        Date  \
82460   rotflmao markets closed monday trusting short ...  2021-05-28   
104750  tsla shit market futures running tesla slightl...  2021-05-14   
64063                       iea added russel spy qqq tsla  2021-06-21   
96763   tsla reason bullish hey nice day trade still g...  2021-05-18   
9053                             aapl today slap ask come  2021-06-14   
22632   bond yields thought meant green spy aapl arkk ...  2021-05-04   
85066                                          tsla crash  2021-05-26   
90495                   tsla better rethink whole outlook  2021-05-21   
23137   aapl got greedy morning staying greedy next hours  2021-05-03   
96667                 tsla still plenty time day price go  2021-05-18   

             Time  Sentiment lang  
82460   20:20:07Z          0   en  
104750  17:42:15Z          1   en  
64063   13:39:11Z          1   en  
96763   15:56:44Z          0   en  
9053    16:09:17Z          0   en  
22632   16:27:31Z          1   en  
85066   16:19:23Z          0   en  
90495   11:18:36Z          1   en  
23137   22:50:26Z          1   en  
96667   16:29:07Z          1   en

On divise ensuite le data set data en test et train 
- train size 80%
- test size 20%

In [4]:
from numpy.random import RandomState

rng = RandomState()
train_data = tweets.sample(frac=0.8, random_state=rng)
test_data = tweets.loc[~tweets.index.isin(train_data.index)]
print('Size of training data:',len(train_data))
print('Size of test data:',len(test_data))

Size of training data: 88784
Size of test data: 22196


#  Model Training - RNN

In [16]:
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout,Activation,Embedding,Bidirectional,SimpleRNN,Flatten
from tensorflow.keras import optimizers

In [6]:
max_features = 20000  # Only consider the top 20k words
maxlen = 200

In [7]:
train_data['flag'] = 'TRAIN'
test_data['flag'] = 'TEST'


total_docs = pd.concat([train_data,test_data],axis = 0,ignore_index = True)
phrases = total_docs['Message'].tolist()

total_docs.sample(10)

<ipython-input-7-a9cd6a1b42ff>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['flag'] = 'TEST'


Message        Date  \
19072                         cciv news tomorrow fly aapl  2021-03-17   
77306   tsla dumping shares tomorrow ask well lost lot...  2021-05-17   
95758       aapl follow follows shoot follow get one back  2021-04-12   
13142   today biggest market cap gainers amazon amzn b...  2021-06-17   
96055   mvis msft aapl sure three come mutually benefi...  2021-04-08   
91795   aapl cnbc comes www cnbc com apple looking str...  2021-05-26   
93329   aapl apple losing lawsuit fornite becareful ap...  2021-05-04   
63962                                     tsla much money  2021-06-24   
109071                       tsla fuck every short doge x  2021-05-17   
60309   aapl really gonna hold onto short position not...  2021-04-09   

             Time  Sentiment lang   flag  
19072   00:14:01Z          1   en  TRAIN  
77306   03:49:47Z          0   en  TRAIN  
95758   00:50:29Z          1   en   TEST  
13142   20:38:03Z          1   en  TRAIN  
96055   01:01:51Z          1   en   TEST  
91795   17:58:27Z          1   en   TEST  
93329   14:20:19Z          0   en   TEST  
63962   15:59:44Z          1   en  TRAIN  
109071  15:19:36Z          1   en   TEST  
60309   14:05:36Z          1   en  TRAIN

In [8]:
from keras.preprocessing.text import one_hot
vocab_size = 20000
encoded_phrases = [one_hot(d, vocab_size) for d in phrases]
total_docs['Phrase'] = encoded_phrases
train_data = total_docs[total_docs['flag'] == 'TRAIN']
test_data = total_docs[total_docs['flag'] == 'TEST']
x_train = train_data['Phrase']
y_train = train_data['Sentiment']
x_val = test_data['Phrase']
y_val = test_data['Sentiment']

We converted the sentence into numbers

In [9]:
print(total_docs['Phrase'][23])

[10755, 1717, 16911, 5256, 13003, 10755, 582, 15771, 6509, 14652, 10655, 8113, 201, 538, 16695, 3950, 3802, 19003, 14650, 3802, 19003, 9471, 7402, 10160, 4292, 16204, 12973, 7840, 918, 16739, 3863, 18905, 13693, 522, 2967, 4876, 12909, 5540]


In [10]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_val = keras.preprocessing.sequence.pad_sequences(x_val, maxlen=maxlen)

In [18]:
model = keras.Sequential()
# Embedding layer turns vectors of integers into dense real vectors of fixed size
model.add(Embedding(max_features, 16, input_length=maxlen))
model.add(SimpleRNN(32, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 200, 16)           320000    
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 200, 32)           1568      
_________________________________________________________________
flatten_1 (Flatten)          (None, 6400)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6401      
Total params: 327,969
Trainable params: 327,969
Non-trainable params: 0
_________________________________________________________________


In [20]:
EPOCHS = 32
BATCH = 128

early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=2)

model.fit(x_train, y_train,
          batch_size=BATCH,
          epochs=EPOCHS,
          validation_data=(x_val, y_val),
          verbose = 1,
          callbacks = [early_stop])

Epoch 1/32
694/694 [==============================] - 48s 69ms/step - loss: 0.4703 - accuracy: 0.7822 - val_loss: 0.4215 - val_accuracy: 0.8119
Epoch 2/32
694/694 [==============================] - 45s 65ms/step - loss: 0.4021 - accuracy: 0.8216 - val_loss: 0.4170 - val_accuracy: 0.8111
Epoch 3/32
694/694 [==============================] - 44s 64ms/step - loss: 0.3881 - accuracy: 0.8275 - val_loss: 0.4104 - val_accuracy: 0.8176
Epoch 4/32
694/694 [==============================] - 44s 63ms/step - loss: 0.3781 - accuracy: 0.8329 - val_loss: 0.4067 - val_accuracy: 0.8197
Epoch 5/32
694/694 [==============================] - 44s 63ms/step - loss: 0.3712 - accuracy: 0.8359 - val_loss: 0.4048 - val_accuracy: 0.8196
Epoch 6/32
694/694 [==============================] - 44s 64ms/step - loss: 0.3654 - accuracy: 0.8400 - val_loss: 0.4081 - val_accuracy: 0.8201
Epoch 7/32
694/694 [==============================] - 44s 63ms/step - loss: 0.3598 - accuracy: 0.8414 - val_loss: 0.4084 - val_accuracy:

In [21]:
print(x_train)
x_train.shape

[[    0     0     0 ... 16859 14894  5277]
 [    0     0     0 ... 19583   798  1717]
 [    0     0     0 ... 15327 13825 12657]
 ...
 [    0     0     0 ... 14469  8623 18656]
 [    0     0     0 ...  5521  1717  3494]
 [    0     0     0 ... 18339  3657  4897]]


(88784, 200)

In [22]:
print(y_train)
y_train.shape

0        1
1        1
2        1
3        0
4        0
        ..
88779    1
88780    1
88781    0
88782    1
88783    1
Name: Sentiment, Length: 88784, dtype: int64


(88784,)

In [23]:
from keras.preprocessing.text import one_hot

test_loss, test_acc = model.evaluate(x=x_val, y=y_val)

print('Test Loss: {}'.format(test_loss))
print('Test Accuracy: {}'.format(test_acc))



694/694 [==============================] - 4s 5ms/step - loss: 0.4084 - accuracy: 0.8185
Test Loss: 0.40839454531669617
Test Accuracy: 0.8184807896614075


# Prediction

In [60]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/AAPL_pred_data.csv'
df = pd.read_csv(file, sep=',')
data_predict = df.drop(['User_id','Unnamed: 0'],axis = 1)
data_predict.reset_index(drop=True, inplace=True)
data_predict.dropna(inplace=True)
data_predict.head()

C:\Users\Harshul\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (2,3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


Message      Date       Time  \
0              $AAPL time to take it to 150 in 1 week  7/6/2021  08:03:11Z   
4                              $AAPL  Slowly going up  7/6/2021  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t...  7/6/2021  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed...  7/6/2021  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t...  7/6/2021  07:38:41Z   

   Sentiment  
0    Bullish  
4    Bullish  
6    Bullish  
7    Bearish  
11   Bullish

In [61]:
import nltk
import re
from nltk.corpus import stopwords
def text_cleaning(text):
    forbidden_words = set(stopwords.words('english'))
    text = ' '.join(text.split('.'))
    text = re.sub('\/',' ',text)
    text = text.strip('\'"')
    text = re.sub(r'@([^\s]+)',r'\1',text)
    text = re.sub(r'\\',' ',text)
    text = text.lower()
    text = re.sub('[\s]+', ' ', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)
    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))',' ',text)
    text = re.sub(r'((http)\S+)','',text)
    text = re.sub(r'\s+', ' ', re.sub('[^A-Za-z]', ' ', text.strip().lower())).strip()
    text = re.sub(r'\W+', ' ', text.strip().lower()).strip()
    text = [word for word in text.split() if word not in forbidden_words]
    return ' '.join(text)

data_predict['Message'] = data_predict['Message'].apply(lambda text: text_cleaning(text))
data_predict.dropna(inplace=True)
data_predict.sample(3)

Message       Date  \
41849  aapl found everybody mom cooks breakfast next day  5/27/2021   
60486                          aapl qqq lets gooo timber   5/6/2021   
20540  aapl mill volume tomorrow would able sleep sho...  6/16/2021   

            Time Sentiment  
41849  15:56:44Z   Bullish  
60486  18:29:18Z   Bearish  
20540  19:26:58Z   Bullish

In [62]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0

L=[]
for row in data_predict['Message']:
    if len(row) >= 3:
        L.append(detect(row))
    else:
        L.append(None)

data_predict['lang'] = L
data_predict.head()

Message      Date       Time  \
0                                 aapl time take week  7/6/2021  08:03:11Z   
4                                   aapl slowly going  7/6/2021  07:57:34Z   
6   sndl many things billion bank debt free cannab...  7/6/2021  07:49:10Z   
7   smartoptions unusual activity alert delayed aa...  7/6/2021  07:44:42Z   
11    aapl time covered calls think reaching cautious  7/6/2021  07:38:41Z   

   Sentiment lang  
0    Bullish   af  
4    Bullish   en  
6    Bullish   en  
7    Bearish   en  
11   Bullish   en

In [63]:
data_predict = data_predict[data_predict["lang"] == 'en']
data_predict.head()

Message      Date       Time  \
4                                   aapl slowly going  7/6/2021  07:57:34Z   
6   sndl many things billion bank debt free cannab...  7/6/2021  07:49:10Z   
7   smartoptions unusual activity alert delayed aa...  7/6/2021  07:44:42Z   
11    aapl time covered calls think reaching cautious  7/6/2021  07:38:41Z   
12  smartoptions unusual activity alert delayed aa...  7/6/2021  07:38:31Z   

   Sentiment lang  
4    Bullish   en  
6    Bullish   en  
7    Bearish   en  
11   Bullish   en  
12   Bearish   en

In [64]:
phrases_pred = data_predict['Message'].tolist()
vocab_size = 20000
encoded_phrases_pred = [one_hot(d, vocab_size) for d in phrases_pred]
data_predict['Phrase'] = encoded_phrases_pred
#train_data = total_docs[total_docs['flag'] == 'TRAIN']
#test_data = total_docs[total_docs['flag'] == 'TEST']
x_pred = data_predict['Phrase']

In [65]:
x_pred = keras.preprocessing.sequence.pad_sequences(x_pred, maxlen=maxlen)

In [66]:
data_predict['probability'] = model.predict(x_pred)
data_predict.head()

Message      Date       Time  \
4                                   aapl slowly going  7/6/2021  07:57:34Z   
6   sndl many things billion bank debt free cannab...  7/6/2021  07:49:10Z   
7   smartoptions unusual activity alert delayed aa...  7/6/2021  07:44:42Z   
11    aapl time covered calls think reaching cautious  7/6/2021  07:38:41Z   
12  smartoptions unusual activity alert delayed aa...  7/6/2021  07:38:31Z   

   Sentiment lang                                             Phrase  \
4    Bullish   en                                [1717, 16995, 2623]   
6    Bullish   en  [5862, 9197, 12714, 3166, 153, 17150, 1202, 55...   
7    Bearish   en  [8817, 13350, 5169, 240, 6048, 1717, 19183, 95...   
11   Bullish   en      [1717, 5277, 7270, 14576, 2212, 16557, 16522]   
12   Bearish   en  [8817, 13350, 5169, 240, 6048, 1717, 19183, 95...   

    probability  
4      0.728071  
6      0.981046  
7      0.051206  
11     0.936977  
12     0.051206

In [67]:
data_predict.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/predicted_prob_RNN_AAPL.csv', sep = ',',index = False)

In [68]:
#data_predict['probability'].min()
data_predict_clean = data_predict.drop(['Message','Sentiment','lang','Phrase','Time'],axis = 1)
data_predict_clean.head()

Date  probability
4   7/6/2021     0.728071
6   7/6/2021     0.981046
7   7/6/2021     0.051206
11  7/6/2021     0.936977
12  7/6/2021     0.051206

In [69]:
data_predict_summed = data_predict_clean.groupby(['Date'], as_index = False)[['probability']].mean()
data_predict_summed.head()

Date  probability
0   5/1/2021     0.820330
1  5/10/2021     0.649200
2  5/11/2021     0.613557
3  5/12/2021     0.590898
4  5/13/2021     0.658957

In [70]:
data_predict_summed

Date  probability
0    5/1/2021     0.820330
1   5/10/2021     0.649200
2   5/11/2021     0.613557
3   5/12/2021     0.590898
4   5/13/2021     0.658957
..        ...          ...
62   7/2/2021     0.805551
63   7/3/2021     0.770363
64   7/4/2021     0.815919
65   7/5/2021     0.769952
66   7/6/2021     0.766284

[67 rows x 2 columns]

In [52]:
data_predict_summed.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/data_predict_summed_RNN_AAPL.csv', sep = ',',index = False)

In [71]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/AAPL_hist_data.csv'
df = pd.read_csv(file, sep=',')
data_hist = df.drop(['High','Low','Adj Close','Volume'],axis = 1)
data_hist.reset_index(drop=True, inplace=True)
data_hist.head()

Date        Open       Close
0  5/3/2021  132.039993  132.539993
1  5/4/2021  131.190002  127.849998
2  5/5/2021  129.199997  128.100006
3  5/6/2021  127.889999  129.740005
4  5/7/2021  130.850006  130.210007

In [72]:
data_predict_summed['Date'] = pd.to_datetime(data_predict_summed['Date'])
data_hist['Date'] = pd.to_datetime(data_hist['Date'])
data_hist = pd.merge(data_hist, data_predict_summed, how="left", on="Date")
data_hist.dropna(inplace=True)
data_hist

Date        Open       Close  probability
0  2021-05-03  132.039993  132.539993     0.794333
1  2021-05-04  131.190002  127.849998     0.679523
2  2021-05-05  129.199997  128.100006     0.698920
3  2021-05-06  127.889999  129.740005     0.792637
4  2021-05-07  130.850006  130.210007     0.748719
5  2021-05-10  129.410004  126.849998     0.649200
6  2021-05-11  123.500000  125.910004     0.613557
7  2021-05-12  123.400002  122.769997     0.590898
8  2021-05-13  124.580002  124.970001     0.658957
9  2021-05-14  126.250000  127.449997     0.756385
10 2021-05-17  126.820000  126.269997     0.674682
11 2021-05-18  126.559998  124.849998     0.677468
12 2021-05-19  123.160004  124.690002     0.602061
13 2021-05-20  125.230003  127.309998     0.794529
14 2021-05-21  127.820000  125.430000     0.724592
15 2021-05-24  126.010002  127.099998     0.748635
16 2021-05-25  127.820000  126.900002     0.780573
17 2021-05-26  126.959999  126.849998     0.784554
18 2021-05-27  126.440002  125.279999     0.732772
19 2021-05-28  125.570000  124.610001     0.700396
20 2021-06-01  125.080002  124.279999     0.724081
21 2021-06-02  124.279999  125.059998     0.708625
22 2021-06-03  124.680000  123.540001     0.710130
23 2021-06-04  124.070000  125.889999     0.785122
24 2021-06-07  126.169998  125.900002     0.769436
25 2021-06-08  126.599998  126.739998     0.786650
26 2021-06-09  127.209999  127.129997     0.748243
27 2021-06-10  127.019997  126.110001     0.690683
28 2021-06-11  126.529999  127.349998     0.759498
29 2021-06-14  127.820000  130.479996     0.787173
30 2021-06-15  129.940002  129.639999     0.709815
31 2021-06-16  130.369995  130.149994     0.650444
32 2021-06-17  129.800003  131.789993     0.706884
33 2021-06-18  130.710007  130.460007     0.733773
34 2021-06-21  130.300003  132.300003     0.736050
35 2021-06-22  132.130005  133.979996     0.802433
36 2021-06-23  133.770004  133.699997     0.805977
37 2021-06-24  134.449997  133.410004     0.794940
38 2021-06-25  133.460007  133.110001     0.748344
39 2021-06-28  133.410004  134.779999     0.774818
40 2021-06-29  134.800003  136.330002     0.811951
41 2021-06-30  136.169998  136.960007     0.784535
42 2021-07-01  136.600006  137.270004     0.781218
43 2021-07-02  137.899994  139.960007     0.805551
44 2021-07-06  140.070007  142.020004     0.766284

In [73]:
data_hist.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/data_hist_cleand_RNN_AAPL.csv', sep = ',',index = False)