In [2]:
import numpy as np 
import pandas as pd 
from textblob import TextBlob
import matplotlib.pyplot as plt

# Reading csv file

In [310]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/TSLAtweets5k.csv'
#df = pd.read_csv(file, sep=',',nrows=10000)
df_2 = pd.read_csv(file, sep=',')
print(df_2.head())

   Unnamed: 0    User_id                                            Message  \
0           0  353007388  $TSLA  SpaceX Is Launching a Rocket the Size o...   
1           1  353007192  $TSLA has been mentioned 3 times on WallStreet...   
2           2  353006941  Recap 7/6:\nGreat start to the week. $SPY puts...   
3           3  353006805  $SPY $TSLA \n\nhttps://mobile.twitter.com/Clar...   
4           4  353006152  $AMC For change you have to work together.\n-T...   

         Date       Time Sentiment  
0  2021-07-07  01:04:41Z       NaN  
1  2021-07-07  01:03:57Z       NaN  
2  2021-07-07  01:02:56Z       NaN  
3  2021-07-07  01:02:26Z   Bearish  
4  2021-07-07  00:59:51Z   Bullish  


In [311]:
file = 'D:/BAIM Academic/Summer Mod 2/ML MGMT 590/AAPLtweets5k.csv'
#df = pd.read_csv(file, sep=',',nrows=10000)
df_1 = pd.read_csv(file, sep=',')
print(df_1.head())

   Unnamed: 0    User_id                                            Message  \
0           0  352604057             $AAPL time to take it to 150 in 1 week   
1           1  352603862  $AAPL In the recent reporting quarter: 25.00% ...   
2           2  352603771  $AAPL We know what a difficult time it has bee...   
3           3  352603702  $AAPL has a Return On Assets of 22.63%. This i...   
4           4  352603496                             $AAPL  Slowly going up   

         Date       Time Sentiment  
0  2021-07-06  08:03:11Z   Bullish  
1  2021-07-06  08:01:29Z       NaN  
2  2021-07-06  08:00:35Z       NaN  
3  2021-07-06  08:00:00Z       NaN  
4  2021-07-06  07:57:34Z   Bullish  


In [354]:
df_2
df_2['Date'] = pd.to_datetime(df_2['Date'])
pred_data = df_2[(df_2['Date'] >= '2021-06-01')]
pred_data.head()
pred_data.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/TSLA_to_pred_data.csv', sep = ',',index = False)

In [312]:
df = pd.concat([df_1, df_2], ignore_index=True)
print(df.head())

   Unnamed: 0    User_id                                            Message  \
0           0  352604057             $AAPL time to take it to 150 in 1 week   
1           1  352603862  $AAPL In the recent reporting quarter: 25.00% ...   
2           2  352603771  $AAPL We know what a difficult time it has bee...   
3           3  352603702  $AAPL has a Return On Assets of 22.63%. This i...   
4           4  352603496                             $AAPL  Slowly going up   

         Date       Time Sentiment  
0  2021-07-06  08:03:11Z   Bullish  
1  2021-07-06  08:01:29Z       NaN  
2  2021-07-06  08:00:35Z       NaN  
3  2021-07-06  08:00:00Z       NaN  
4  2021-07-06  07:57:34Z   Bullish  


# Data Cleaning

In [313]:
df.describe()

Unnamed: 0       User_id
count  299986.000000  2.999860e+05
mean    74996.000030  3.315685e+08
std     43299.321683  1.434288e+07
min         0.000000  2.997594e+08
25%     37498.000000  3.225103e+08
50%     74996.000000  3.330402e+08
75%    112494.000000  3.429894e+08
max    149995.000000  3.530074e+08

In [314]:
pip install textblob

In [316]:
data = df.drop(['User_id','Unnamed: 0'],axis = 1)
data.reset_index(drop=True, inplace=True)
data.dropna(inplace=True)
data.head()


Message        Date       Time  \
0              $AAPL time to take it to 150 in 1 week  2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up  2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t...  2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed...  2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t...  2021-07-06  07:38:41Z   

   Sentiment  
0    Bullish  
4    Bullish  
6    Bullish  
7    Bearish  
11   Bullish

In [317]:
data["Sentiment"].replace({"Bullish": "1", "Bearish": "0"}, inplace=True)
data.head()

Message        Date       Time  \
0              $AAPL time to take it to 150 in 1 week  2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up  2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t...  2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed...  2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t...  2021-07-06  07:38:41Z   

   Sentiment  
0          1  
4          1  
6          1  
7          0  
11         1

In [318]:
data = data.astype({'Sentiment': 'int32'})
data.dtypes

Message      object
Date         object
Time         object
Sentiment     int32
dtype: object

In [319]:
data['Date'] = pd.to_datetime(data['Date'])
#data = data[(data['timestamp'] >= '2017-01-01')]
data.head()

Message       Date       Time  \
0              $AAPL time to take it to 150 in 1 week 2021-07-06  08:03:11Z   
4                              $AAPL  Slowly going up 2021-07-06  07:57:34Z   
6   $SNDL \nSo many things\n- about a BILLION in t... 2021-07-06  07:49:10Z   
7   SmartOptions® Unusual Activity Alert\n(Delayed... 2021-07-06  07:44:42Z   
11  $AAPL when is  the time for covered calls? I t... 2021-07-06  07:38:41Z   

    Sentiment  
0           1  
4           1  
6           1  
7           0  
11          1

In [320]:
tweets = data['Message']
print(tweets[4])

$AAPL  Slowly going up


In [28]:
pip install langdetect

  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993227 sha256=8e249feb667af40e3b3f8785c073139ce096342c33a1b8f4aaaf7203f0fe1420
  Stored in directory: c:\users\harshul\appdata\local\pip\cache\wheels\13\c7\b0\79f66658626032e78fc1a83103690ef6797d551cb22e56e734
Successfully built langdetect
Note: you may need to restart the kernel to use updated packages.


In [321]:
import nltk
import re
from nltk.corpus import stopwords

def text_cleaning(text):
    forbidden_words = set(stopwords.words('english'))
    text = ' '.join(text.split('.'))
    text = re.sub('\/',' ',text)
    text = text.strip('\'"')
    text = re.sub(r'@([^\s]+)',r'\1',text)
    text = re.sub(r'\\',' ',text)
    text = text.lower()
    text = re.sub('[\s]+', ' ', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)
    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))',' ',text)
    text = re.sub(r'((http)\S+)','',text)
    text = re.sub(r'\s+', ' ', re.sub('[^A-Za-z]', ' ', text.strip().lower())).strip()
    text = re.sub(r'\W+', ' ', text.strip().lower()).strip()
    text = [word for word in text.split() if word not in forbidden_words]
    return ' '.join(text)

data['Message'] = data['Message'].apply(lambda text: text_cleaning(text))
data.sample(3)

Message       Date  \
76255                                           told aapl 2021-04-28   
147173           aapl gosh please help apple follow trend 2021-03-08   
21523   gm aapl flight apple shares either way flight ... 2021-06-16   

             Time  Sentiment  
76255   20:46:21Z          1  
147173  14:05:50Z          1  
21523   17:05:12Z          1

In [325]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0
#detect("War doesn't show who's right, just who's left.")

L=[]
for row in data['Message']:
    if len(row) >= 3:
        L.append(detect(row))
    else:
        L.append(None)

data['lang'] = L
data.head()

Message       Date       Time  \
0                                 aapl time take week 2021-07-06  08:03:11Z   
4                                   aapl slowly going 2021-07-06  07:57:34Z   
6   sndl many things billion bank debt free cannab... 2021-07-06  07:49:10Z   
7   smartoptions unusual activity alert delayed aa... 2021-07-06  07:44:42Z   
11    aapl time covered calls think reaching cautious 2021-07-06  07:38:41Z   

    Sentiment lang  
0           1   af  
4           1   en  
6           1   en  
7           0   en  
11          1   en

In [326]:
data = data[data["lang"] == 'en']
data.head()

Message       Date       Time  \
4                                   aapl slowly going 2021-07-06  07:57:34Z   
6   sndl many things billion bank debt free cannab... 2021-07-06  07:49:10Z   
7   smartoptions unusual activity alert delayed aa... 2021-07-06  07:44:42Z   
11    aapl time covered calls think reaching cautious 2021-07-06  07:38:41Z   
12  smartoptions unusual activity alert delayed aa... 2021-07-06  07:38:31Z   

    Sentiment lang  
4           1   en  
6           1   en  
7           0   en  
11          1   en  
12          0   en

In [328]:
data.describe()

Sentiment
count  110980.000000
mean        0.719724
std         0.449136
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000

In [327]:
data['Sentiment'].astype('int64').sum()

79875

In [3]:
data.to_csv('D:/BAIM Academic/Summer Mod 2/ML MGMT 590/my_clean_tweets.csv', sep = ',',index = False)

tweets=pd.read_csv('/Users/saksheeagarwal/Downloads/my_clean_tweets.csv', sep=',')
tweets.sample(10)

Message        Date  \
17034                        aapl timbercorp timber crap  2021-05-19   
6640            aapl told bears secure profits yesterday  2021-06-17   
45932  tsla yields rising fyi aapl tell lot tsla big ...  2021-03-11   
18720  edtk super undervalued valuation holding till ...  2021-05-13   
31167  aapl come guys got friday cook calls get anymo...  2021-04-20   
19185         qqq cant even bounce cents timbercorp aapl  2021-05-12   
21817  aapl amzn fb strong earnings companies true le...  2021-05-05   
9140   aapl diabetic market huge pun intended adding ...  2021-06-14   
14920                        aapl fish smell like shower  2021-05-27   
19230  market losing altitude much higher interest ra...  2021-05-12   

       Sentiment lang  
17034          0   en  
6640           1   en  
45932          0   en  
18720          1   en  
31167          1   en  
19185          0   en  
21817          1   en  
9140           1   en  
14920          1   en  
19230          0   en

On divise ensuite le data set data en test et train 
- train size 80%
- test size 20%

In [4]:
from numpy.random import RandomState

rng = RandomState()
train_data = tweets.sample(frac=0.8, random_state=rng)
test_data = tweets.loc[~tweets.index.isin(train_data.index)]
print('Size of training data:',len(train_data))
print('Size of test data:',len(test_data))

Size of training data: 39762
Size of test data: 9940


#  Model Training - BiDirectional LSTM

In [5]:
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout,Activation,Embedding,Bidirectional
from tensorflow.keras import optimizers

In [6]:
max_features = 20000  # Only consider the top 20k words
maxlen = 200

In [7]:
train_data['flag'] = 'TRAIN'
test_data['flag'] = 'TEST'


total_docs = pd.concat([train_data,test_data],axis = 0,ignore_index = True)
phrases = total_docs['Message'].tolist()

total_docs.sample(10)

<ipython-input-7-a9cd6a1b42ff>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['flag'] = 'TEST'


Message        Date  \
36783  aapl june china time alibaba mid year shopping...  2021-06-16   
39126  aapl small differnece pump amp dump rally usua...  2021-06-28   
26565  aapl heard rumor brokerages advised exercise m...  2021-03-08   
1144                                aapl due bounce back  2021-04-20   
16192  anyone pick aapl week easy money yesterday gre...  2021-03-11   
7766                    qcom aapl guarantee go red today  2021-05-13   
31967  aapl trillion dollar company prints money tim ...  2021-04-30   
14322  aapl ready buy signal anything around bit lowe...  2021-04-21   
26494  aapl best stock times time touching small news...  2021-04-07   
42371                          aapl clown claiming today  2021-06-02   

       Sentiment lang   flag  
36783          1   en  TRAIN  
39126          0   en  TRAIN  
26565          1   en  TRAIN  
1144           1   en  TRAIN  
16192          1   en  TRAIN  
7766           0   en  TRAIN  
31967          1   en  TRAIN  
14322          1   en  TRAIN  
26494          1   en  TRAIN  
42371          1   en   TEST

In [8]:
from keras.preprocessing.text import one_hot
vocab_size = 20000
encoded_phrases = [one_hot(d, vocab_size) for d in phrases]
total_docs['Phrase'] = encoded_phrases
train_data = total_docs[total_docs['flag'] == 'TRAIN']
test_data = total_docs[total_docs['flag'] == 'TEST']
x_train = train_data['Phrase']
y_train = train_data['Sentiment']
x_val = test_data['Phrase']
y_val = test_data['Sentiment']

We converted the sentence into numbers

In [9]:
print(total_docs['Phrase'][23])

[13441, 17350, 9984, 9813, 13232]


In [10]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=maxlen)
x_val = keras.preprocessing.sequence.pad_sequences(x_val, maxlen=maxlen)

In [11]:
model = keras.Sequential()
# Embedding layer turns vectors of integers into dense real vectors of fixed size
model.add(Embedding(max_features, 16))
model.add(Bidirectional(LSTM(128, return_sequences=False, dropout=0.2, recurrent_dropout=0.2)))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          320000    
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               148480    
_________________________________________________________________
dense (Dense)                (None, 1)                 257       
Total params: 468,737
Trainable params: 468,737
Non-trainable params: 0
_________________________________________________________________


In [12]:
EPOCHS = 32
BATCH = 128

early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=2)

model.fit(x_train, y_train,
          batch_size=BATCH,
          epochs=EPOCHS,
          validation_data=(x_val, y_val),
          verbose = 1,
          callbacks = [early_stop])

Epoch 1/32
311/311 [==============================] - 234s 671ms/step - loss: 0.5558 - accuracy: 0.7534 - val_loss: 0.4122 - val_accuracy: 0.8184
Epoch 2/32
311/311 [==============================] - 220s 707ms/step - loss: 0.3927 - accuracy: 0.8312 - val_loss: 0.3792 - val_accuracy: 0.8407
Epoch 3/32
311/311 [==============================] - 223s 715ms/step - loss: 0.3556 - accuracy: 0.8498 - val_loss: 0.3728 - val_accuracy: 0.8431
Epoch 4/32
311/311 [==============================] - 232s 746ms/step - loss: 0.3436 - accuracy: 0.8550 - val_loss: 0.3721 - val_accuracy: 0.8416
Epoch 5/32
311/311 [==============================] - 257s 825ms/step - loss: 0.3326 - accuracy: 0.8604 - val_loss: 0.3689 - val_accuracy: 0.8410
Epoch 6/32
311/311 [==============================] - 251s 808ms/step - loss: 0.3238 - accuracy: 0.8638 - val_loss: 0.3679 - val_accuracy: 0.8416
Epoch 7/32
311/311 [==============================] - 281s 901ms/step - loss: 0.3185 - accuracy: 0.8678 - val_loss: 0.3730 -

In [13]:
print(x_train)
x_train.shape

[[    0     0     0 ...  7653  2421 11528]
 [    0     0     0 ... 19876 17549 16615]
 [    0     0     0 ...  1441  3546 12920]
 ...
 [    0     0     0 ... 18168 13507  8631]
 [    0     0     0 ...  2650 11709   353]
 [    0     0     0 ...  9025  1911 17915]]


(39762, 200)

In [14]:
print(y_train)
y_train.shape

0        0
1        1
2        1
3        1
4        1
        ..
39757    1
39758    1
39759    1
39760    0
39761    0
Name: Sentiment, Length: 39762, dtype: int64


(39762,)

In [15]:
from keras.preprocessing.text import one_hot

test_loss, test_acc = model.evaluate(x=x_val, y=y_val)

print('Test Loss: {}'.format(test_loss))
print('Test Accuracy: {}'.format(test_acc))



311/311 [==============================] - 25s 81ms/step - loss: 0.3692 - accuracy: 0.8466
Test Loss: 0.369210422039032
Test Accuracy: 0.8465794920921326


# Prediction 

In [16]:
file = '/Users/saksheeagarwal/Downloads/TSLA_to_pred_data.csv'
df = pd.read_csv(file, sep=',')
data_predict = df.drop(['User_id','Unnamed: 0'],axis = 1)
data_predict.reset_index(drop=True, inplace=True)
data_predict.dropna(inplace=True)
data_predict.head()

Message        Date       Time  \
3   $SPY $TSLA \n\nhttps://mobile.twitter.com/Clar...  2021-07-07  01:02:26Z   
4   $AMC For change you have to work together.\n-T...  2021-07-07  00:59:51Z   
6   SmartOptions® Unusual Activity Alert\n(Delayed...  2021-07-07  00:56:52Z   
7   $RIDE Your rear view mirror after buying a Lor...  2021-07-07  00:55:16Z   
10  $TSLA Look, I&#39;m not Albert Einstein, but I...  2021-07-07  00:54:24Z   

   Sentiment  
3    Bearish  
4    Bullish  
6    Bullish  
7    Bullish  
10   Bearish

In [19]:
import nltk
import re
from nltk.corpus import stopwords

def text_cleaning(text):
    forbidden_words = set(stopwords.words('english'))
    text = ' '.join(text.split('.'))
    text = re.sub('\/',' ',text)
    text = text.strip('\'"')
    text = re.sub(r'@([^\s]+)',r'\1',text)
    text = re.sub(r'\\',' ',text)
    text = text.lower()
    text = re.sub('[\s]+', ' ', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)
    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))',' ',text)
    text = re.sub(r'((http)\S+)','',text)
    text = re.sub(r'\s+', ' ', re.sub('[^A-Za-z]', ' ', text.strip().lower())).strip()
    text = re.sub(r'\W+', ' ', text.strip().lower()).strip()
    text = [word for word in text.split() if word not in forbidden_words]
    return ' '.join(text)

data_predict['Message'] = data_predict['Message'].apply(lambda text: text_cleaning(text))
data_predict.dropna(inplace=True)
data_predict.sample(3)

Message        Date  \
75455  tsla sell tesla spy car china many cars car ac...  2021-06-02   
78701  bubble shit pop like question question tsla gm...  2021-06-01   
30026                                   tsla could today  2021-06-23   

            Time Sentiment  
75455  16:37:03Z   Bearish  
78701  02:22:57Z   Bearish  
30026  15:03:15Z   Bullish

In [20]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0

L=[]
for row in data_predict['Message']:
    if len(row) >= 3:
        L.append(detect(row))
    else:
        L.append(None)

data_predict['lang'] = L
data_predict.head()

Message        Date       Time  \
3   spy tsla mobile twitter com clarkemicah status...  2021-07-07  01:02:26Z   
4   amc change work together greed puts mm sneaky ...  2021-07-07  00:59:51Z   
6   smartoptions unusual activity alert delayed ts...  2021-07-07  00:56:52Z   
7   ride rear view mirror buying lordstown enduran...  2021-07-07  00:55:16Z   
10  tsla look albert einstein good follow anyone w...  2021-07-07  00:54:24Z   

   Sentiment lang  
3    Bearish   en  
4    Bullish   en  
6    Bullish   en  
7    Bullish   en  
10   Bearish   en

In [34]:
data_predict = data_predict[data_predict["lang"] == 'en']
data_predict.to_csv('/Users/saksheeagarwal/Downloads/topredict.csv', sep = ',',index = False)
data_predict.head()

Message        Date       Time  \
3   spy tsla mobile twitter com clarkemicah status...  2021-07-07  01:02:26Z   
4   amc change work together greed puts mm sneaky ...  2021-07-07  00:59:51Z   
6   smartoptions unusual activity alert delayed ts...  2021-07-07  00:56:52Z   
7   ride rear view mirror buying lordstown enduran...  2021-07-07  00:55:16Z   
10  tsla look albert einstein good follow anyone w...  2021-07-07  00:54:24Z   

   Sentiment lang                                             Phrase  \
3    Bearish   en  [13507, 10143, 668, 18136, 8620, 17963, 10677,...   
4    Bullish   en  [13917, 10648, 10337, 1704, 1936, 15718, 14380...   
6    Bullish   en  [13818, 17154, 16429, 4662, 10298, 10143, 8227...   
7    Bullish   en  [17915, 16861, 2, 10289, 5149, 6857, 10150, 56...   
10   Bearish   en  [10143, 1486, 11244, 50, 14706, 17051, 13068, ...   

    probability  
3      0.047542  
4      0.933919  
6      0.991538  
7      0.967735  
10     0.824101

In [22]:
phrases_pred = data_predict['Message'].tolist()
vocab_size = 20000
encoded_phrases_pred = [one_hot(d, vocab_size) for d in phrases_pred]
data_predict['Phrase'] = encoded_phrases_pred
#train_data = total_docs[total_docs['flag'] == 'TRAIN']
#test_data = total_docs[total_docs['flag'] == 'TEST']
x_pred = data_predict['Phrase']

In [23]:
x_pred = keras.preprocessing.sequence.pad_sequences(x_pred, maxlen=maxlen)

In [24]:
data_predict['probability'] = model.predict(x_pred)
data_predict.head()

Message        Date       Time  \
3   spy tsla mobile twitter com clarkemicah status...  2021-07-07  01:02:26Z   
4   amc change work together greed puts mm sneaky ...  2021-07-07  00:59:51Z   
6   smartoptions unusual activity alert delayed ts...  2021-07-07  00:56:52Z   
7   ride rear view mirror buying lordstown enduran...  2021-07-07  00:55:16Z   
10  tsla look albert einstein good follow anyone w...  2021-07-07  00:54:24Z   

   Sentiment lang                                             Phrase  \
3    Bearish   en  [13507, 10143, 668, 18136, 8620, 17963, 10677,...   
4    Bullish   en  [13917, 10648, 10337, 1704, 1936, 15718, 14380...   
6    Bullish   en  [13818, 17154, 16429, 4662, 10298, 10143, 8227...   
7    Bullish   en  [17915, 16861, 2, 10289, 5149, 6857, 10150, 56...   
10   Bearish   en  [10143, 1486, 11244, 50, 14706, 17051, 13068, ...   

    probability  
3      0.047542  
4      0.933919  
6      0.991538  
7      0.967735  
10     0.824101

In [25]:
data_predict.to_csv('/Users/saksheeagarwal/Downloads/predicted_prob.csv', sep = ',',index = False)

In [26]:
#data_predict['probability'].min()
data_predict_clean = data_predict.drop(['Message','Sentiment','lang','Phrase','Time'],axis = 1)
data_predict_clean.head()

Date  probability
3   2021-07-07     0.047542
4   2021-07-07     0.933919
6   2021-07-07     0.991538
7   2021-07-07     0.967735
10  2021-07-07     0.824101

In [27]:
data_predict_summed = data_predict_clean.groupby(['Date'], as_index = False)[['probability']].mean()
data_predict_summed.head()

Date  probability
0  2021-06-01     0.830613
1  2021-06-02     0.811459
2  2021-06-03     0.772505
3  2021-06-04     0.799579
4  2021-06-05     0.847873

In [28]:
data_predict_summed

Date  probability
0   2021-06-01     0.830613
1   2021-06-02     0.811459
2   2021-06-03     0.772505
3   2021-06-04     0.799579
4   2021-06-05     0.847873
5   2021-06-06     0.844117
6   2021-06-07     0.818613
7   2021-06-08     0.813555
8   2021-06-09     0.819423
9   2021-06-10     0.820987
10  2021-06-11     0.834182
11  2021-06-12     0.798752
12  2021-06-13     0.819970
13  2021-06-14     0.821713
14  2021-06-15     0.807667
15  2021-06-16     0.799307
16  2021-06-17     0.818976
17  2021-06-18     0.825861
18  2021-06-19     0.856992
19  2021-06-20     0.869578
20  2021-06-21     0.821391
21  2021-06-22     0.808279
22  2021-06-23     0.826567
23  2021-06-24     0.826068
24  2021-06-25     0.819517
25  2021-06-26     0.813433
26  2021-06-27     0.771195
27  2021-06-28     0.826967
28  2021-06-29     0.823508
29  2021-06-30     0.818521
30  2021-07-01     0.827632
31  2021-07-02     0.830154
32  2021-07-03     0.846129
33  2021-07-04     0.863594
34  2021-07-05     0.869272
35  2021-07-06     0.811488
36  2021-07-07     0.832451

In [29]:
data_predict_summed.to_csv('/Users/saksheeagarwal/Downloads/data_predict_summed.csv', sep = ',',index = False)

In [30]:
file = '/Users/saksheeagarwal/Downloads/TSLAHist.csv'
df = pd.read_csv(file, sep=',')
data_hist = df.drop(['High','Low','Adj Close','Volume'],axis = 1)
data_hist.reset_index(drop=True, inplace=True)
data_hist.head()

Date        Open       Close
0  6/1/2021  627.799988  623.900024
1  6/2/2021  620.130005  605.119995
2  6/3/2021  601.799988  572.840027
3  6/4/2021  579.710022  599.049988
4  6/7/2021  591.830017  605.130005

In [31]:
data_predict_summed['Date'] = pd.to_datetime(data_predict_summed['Date'])
data_hist['Date'] = pd.to_datetime(data_hist['Date'])
data_hist = pd.merge(data_hist, data_predict_summed, how="left", on="Date")
data_hist.dropna(inplace=True)
data_hist

Date        Open       Close  probability
0  2021-06-01  627.799988  623.900024     0.830613
1  2021-06-02  620.130005  605.119995     0.811459
2  2021-06-03  601.799988  572.840027     0.772505
3  2021-06-04  579.710022  599.049988     0.799579
4  2021-06-07  591.830017  605.130005     0.818613
5  2021-06-08  623.010010  603.590027     0.813555
6  2021-06-09  602.169983  598.780029     0.819423
7  2021-06-10  603.880005  610.119995     0.820987
8  2021-06-11  610.229980  609.890015     0.834182
9  2021-06-14  612.229980  617.690002     0.821713
10 2021-06-15  616.690002  599.359985     0.807667
11 2021-06-16  597.539978  604.869995     0.799307
12 2021-06-17  601.890015  616.599976     0.818976
13 2021-06-18  613.369995  623.309998     0.825861
14 2021-06-21  624.479980  620.830017     0.821391
15 2021-06-22  618.250000  623.710022     0.808279
16 2021-06-23  632.000000  656.570007     0.826567
17 2021-06-24  674.989990  679.820007     0.826068
18 2021-06-25  689.580017  671.869995     0.819517
19 2021-06-28  671.640015  688.719971     0.826967
20 2021-06-29  684.650024  680.760010     0.823508
21 2021-06-30  679.770020  679.700012     0.818521

In [33]:
data_hist.to_csv('/Users/saksheeagarwal/Downloads/data_hist_cleand.csv', sep = ',',index = False)